### ISSUE TITLE
Cursor, and character under cursor, are difficult to see in highlighted text

### ISSUE THREAD

**Issue by heygarrett** [daschw/leaf.nvim#4] opened 2022-07-04 14:14 UTC
The darker the theme the more difficult it is to distinguish the cursor, and the character under it, in highlighted text (I searched for the spaces between brackets using `/- \[\zs`).

dark:  
<img width="196" alt="Screen Shot 2022-07-04 at 10 03 08" src="https://user-images.githubusercontent.com/1154912/177172011-34c084c6-beca-4ac4-ad80-0d031ffd5456.png">

darker:  
<img width="196" alt="Screen Shot 2022-07-04 at 10 08 54" src="https://user-images.githubusercontent.com/1154912/177172047-830213b2-d3a5-4d93-aa47-fb8d82ecea82.png">

darkest:  
<img width="196" alt="Screen Shot 2022-07-04 at 10 09 42" src="https://user-images.githubusercontent.com/1154912/177172108-31bc1d17-c33e-4e25-a817-a44888845f83.png">

**Comment by heygarrett** [comment] 2022-07-04 21:00
It seems to be related to the leaf theme for kitty; removing the kitty theme resolves the problem:  
<img width="196" alt="Screen Shot 2022-07-04 at 16 58 19" src="https://user-images.githubusercontent.com/1154912/177216053-142f899d-28ec-4559-a99c-bd8f18b32844.png">

**Comment by daschw** [comment] 2022-07-05 13:27
Thanks again for reporting and finding out that the issue is in the kitty themes. This should now be fixed. However, now the cursor and the highlighted search look exactly the same (when using the kitty themes). Maybe I should consider a different color for search highlights, any preferences?

**Comment by daschw** [comment] 2022-07-05 14:02
Actually the cursor is not visible at all now, so I can't close this yet.

**Closed as completed** 2022-07-05 14:21 UTC

**Comment by heygarrett** [comment] 2022-07-05 14:57
It looks great! Well done. 😊
